# Numpy

- Algorithm: a process or set of rules used for calculation or problem-solving, esp. with a computer.
- A data structure is a specialized format for organizing and storing data. General data structure types include the array, the file, the record, the table, the tree, and so on. Any data structure is designed to organize data to suit a specific purpose so that it can be accessed and worked with in appropriate ways. In computer programming, a data structure may be selected or designed to store data for the purpose of working on it with various algorithms.

- A 'kernel' is a program that runs and introspects the user's code.

In [1]:
import numpy as np

In [10]:
a = np.arange(15).reshape(5,3)

In [11]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [5]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [12]:
a_b = np.array([2,3,4,5,6])

In [13]:
a_b

array([2, 3, 4, 5, 6])

In [14]:
a_b(dtype)

NameError: name 'dtype' is not defined

In [15]:
a_b.dtype

dtype('int64')

In [16]:
b = np.array([1,2,3,4],[3,4,5,6])

TypeError: data type not understood

In [20]:
b = np.array([(1,2,3,4),(3,4,5,6)])

In [21]:
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [22]:
c = np.array( [ (1,2), (3,4) ], dtype=complex )

In [23]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [24]:
c.size

4

In [26]:
c.shape


(2, 2)

In [27]:
c.ndim

2

In [28]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [35]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [30]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [31]:
np.empty( (2,3) ) 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [32]:
np.empty( (2,3,5) ) 

array([[[  0.00000000e+000,   0.00000000e+000,   1.38338381e-322,
           0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000]],

       [[  2.12199579e-314,   0.00000000e+000,   0.00000000e+000,
           9.88131292e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000]]])

in arange function 3 elements signify start, stop and step.

In [36]:
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [37]:
np.arange( 0, 0.3, 2 ) 

array([ 0.])

- start
The first value in the sequence.

- stop
The limiting value: the last element of the sequence will never be greater than or equal to this value (assuming that the step value is positive; for negative step values, the last element of the sequence will always be greater than the stop value).

- print np.arange(1.0, 4.0)
    [ 1.  2.  3.]
    If you omit the stop value, you will get a sequence starting at zero and using start as the limiting value.

- print np.arange(4)
    [0 1 2 3]
    step
    The common difference between successive values of the array. The default value is one.

- dtype
    Use this argument to force representation using a specific type.

 -print np.arange(10)
    [0 1 2 3 4 5 6 7 8 9]
- print np.arange(10, dtype=np.float_)
    [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [41]:
from numpy import pi
np.linspace( 0, 2, 9 ) 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

- When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [40]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [42]:
z = np.linspace( 0, 2*pi, 100 )

In [43]:
z

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [44]:
pi

3.141592653589793

In [45]:
abc = np.sin(30)

In [46]:
abc

-0.98803162409286183

In [47]:
arr = np.arange(6)

In [48]:
arr

array([0, 1, 2, 3, 4, 5])

In [51]:
arr1 = np.arange(12).reshape(4,3)

In [52]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is inferred
        from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the elements
        into the reshaped array using this index order.  'C' means to
        read / write the elements using C-like index order, with the last axis
        index changing fastest, back to the first axis index changing slowest.
        'F' means to read / write the elements using Fortran-like index order,
        with the firs

In [55]:
arr2 = np.arange(20).reshape(2,5,2)

In [56]:
arr2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [57]:
x = ([2,3,4,5])

In [58]:
5 *  np.sin(x)

array([ 4.54648713,  0.70560004, -3.78401248, -4.79462137])

In [59]:
x < 20

TypeError: '<' not supported between instances of 'list' and 'int'

In [60]:
z = np.array([2,3,4,5,6])

In [61]:
z <35

array([ True,  True,  True,  True,  True], dtype=bool)

In [62]:
A = np.array( [[1,1],[0,1]] )


In [63]:

B = np.array( [[2,0], [3,4]] )

In [64]:
A*B

array([[2, 0],
       [0, 4]])

In [65]:
A dot(B)

SyntaxError: invalid syntax (<ipython-input-65-9bed704c507c>, line 1)

In [66]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [67]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

 ## *Examples:*

In [68]:
a = np.ones((2,3), dtype=int)

In [69]:
a *= 3

In [70]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [71]:
b = np.random.random((2,3))

In [72]:
b 

array([[ 0.55246115,  0.04211002,  0.4061733 ],
       [ 0.25237816,  0.59741504,  0.2664256 ]])

In [73]:
b += a

In [74]:
b

array([[ 3.55246115,  3.04211002,  3.4061733 ],
       [ 3.25237816,  3.59741504,  3.2664256 ]])

In [75]:
a += b  

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [76]:
a = np.random.random((2,3))

In [77]:
a

array([[ 0.13203808,  0.1680991 ,  0.79016813],
       [ 0.04898994,  0.94134594,  0.66060954]])

In [78]:
a.sum()

2.7412507378662379

In [79]:
a.min()

0.048989944630524085

In [80]:
print('here')


here
